package com.nikan.epuzzle.exception;

public enum MessageCode {
    // Error messages
    EMAIL_ALREADY_REGISTERED,
    USERNAME_ALREADY_TAKEN,
    INVALID_EMAIL_OR_PASSWORD,
    EMAIL_NOT_VERIFIED,
    USER_NOT_FOUND,
    INVALID_OR_EXPIRED_CODE,
    EMAIL_NOT_FOUND,
    EMAIL_NOT_VERIFIED_FOR_RESET,
    CURRENT_PASSWORD_INCORRECT,
    INVALID_AUTHORIZATION,
    INVALID_TOKEN,
    UNKNOWN_ERROR,
    EMAIL_ALREADY_VERIFIED,

    // Success messages
    SIGNUP_SUCCESS,
    RESET_CODE_SENT,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_CHANGE_CODE_SENT,
    PASSWORD_CHANGE_SUCCESS,
    TOKEN_VALID,
    RESEND_CODE_SUCCESS
}